### PR TITLE
Fixed some buttons and titles not having colors applied

### PR DESCRIPTION
**Pull request by odiffey**
Examples:
image
image

### CODE REVIEW

**Comment by odiffey** [comment]
Sorry just realised this breaks some things if you dont have a transparent header so probably dont want to merge.

**Comment by Red-M** [comment]
If you want to add an option to turn on a transparent header then this is fine.

**Comment by odiffey** [comment]
Sorry for the spam, I kept missing a line off the config. Should be all working now, note that I havent edited the template_css_vars.css

**Comment by Red-M** [comment]
No worries!
I'll take this as is and I might need to switch to jinja2/mako templating instead because its a little much now to do conditionals.

**Pull request merged**
